### PR TITLE
[WFCORE-1806] Split of DomainModelControllerService initialization work

### PR DESCRIPTION
**Pull request by bstansberry**
@pferraro @luck3y please review

I filed separate PRs against the main wildfly-core repo for the first 2 commits.

### CODE REVIEW

**Review by luck3y — APPROVED** [review]
@bstansberry Looks good. I'll clone this later today and give it a go.

**Comment by bstansberry** [comment]
The WFCORE-1781 bit doesn't seem to actually work so I need to fix that. (https://github.com/wildfly/wildfly-core/pull/1788 is for that alone, and I put a Hold label on it until I had a chance to check its correctness. Fail....)

I'll also need to fix up the "Clean out dead code before possible refactor" commit, into which some unrelated code sneakily snuck.

**Comment by bstansberry** [comment]
Ok, should be good now. https://ci.wildfly.org/viewLog.html?buildId=27030&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreIntegrationExperiments is a custom run of this branch.

**Comment by bstansberry** [comment]
@luck3y @pferraro I'm going to close this as I realize now that's it's not really a coherent piece of work. I'll keep the branch alive and won't alter these commits beyond rebasing on master (so if you are counting on the history it will remain.) But it's too small a piece to count as something 'complete'.

It's ok as the base for the case where an HC boots and then somehow or other an election will happen and one or the other of the 'master' or 'slave' services gets started. But it completely leaves out subsequent transitions that might occur. HC is master and gets deposed. HC is slave and later gets elected master. Right now a clean transition like that would require a reload and that is inadequate.

**Pull request closed without merging**
